services:
  oracledb:
    image: container-registry.oracle.com/database/free:latest
    environment:
      - ORACLE_PWD=admin123
    ports:
      - 1521:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "ls"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  oracle-data:
  redis-data: