version: "3.8"

services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    ports:
      - "1521:1521"
      - "8080:8080"
    environment:
      ORACLE_PASSWORD: swsadmin
      APP_USER: huey
      APP_USER_PASSWORD: hueyadmin
    volumes:
      - oracle-data:/opt/oracle/oradata

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  oracle-data:
